config/routes.rb
Rails.application.routes.draw do
  resources :notes
  
  # get '/notes/index' => 'notes#index'
  
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_notes
    end
  end

  resources :notes, only: [:show, :create, :edit, :update, :destroy] do
    member do
      get :liking_users
    end
  end

  post '/like/:note_id' => 'likes#like', as: 'like'
  delete '/unlike/:note_id' => 'likes#unlike', as: 'unlike'
  

  
  root 'home#top'
  get '/about' => 'home#about'
  
  resources :notes, :proposals do
  collection do
    post :import
  end
end

class CsvExportConstraint
  def self.matches?(request)
    request.params.has_key?(:export_csv)
  end
end

Rails.application.routes.draw do
  # root 'notes#index'

  resources :notes, only: [:index] do
    collection do
      get :index, action: :export_csv, constraints: CsvExportConstraint
      get :index
    end
  end
end

  
  
end

app/models/note.rb
require 'csv'
require 'nkf'
# require 'cocoon'
# require 'kconv'
class Note < ActiveRecord::Base
  belongs_to :user
  
  has_many :proposals, dependent: :destroy
  accepts_nested_attributes_for :proposals, reject_if: :all_blank, allow_destroy: true
  

  
  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
  validates :sales_company, presence: true
  validates :end_user, presence: true
  validates :delivery_day, presence: true
  validates :status, presence: true
  validates :proposals, presence: true
  records_with_operator_on :update

  def previous
    Note.where("id < ?", self.id).order("id DESC").first
  end

  def next
    Note.where("id > ?", self.id).order("id ASC").first
  end  
  
  def self.to_csv
  csv_data = CSV.generate("", {:row_sep => "\r\n", :force_quotes => true}) do |csv|
  csv_column_names = %w(ID 担当 市場 販社 EU 機種 台数 価格 納期 状態)
  csv << csv_column_names
  all.each do |note|
    note.proposals.each do |proposal|
    csv_column_values = [
      note.id,
      note.user.name,
      note.title,
      note.sales_company,
      note.end_user,
      proposal.model,
      proposal.quantity,
      proposal.price,
      note.delivery_day,
      note.status
      ]
    csv << csv_column_values
    end
  end
  end
  NKF::nkf('--sjis -Lw', csv_data)
  end


  def self.import(file)
  csv_text = File.read('db/file.csv')
  csv = CSV.parse(csv_text, :headers => true ,header_converters: :symbol)
  csv.each do |row|
    # Note.create!(row.to_hash)
    # title,sales_company,end_user,user_id,delivery_day,content,status,model,quantity,price
  
    # Note.create!(:title => row[0],
    #                 :sales_company => row[1],
    #                 :end_user => row[2],
    #                 :user_id => row[4],
    #                 :delivery_day => row[3],
    #                 :content => row[5],
    #                 :status => row[6])
    Proposal.create!(:model => row[0],
                    :quantity => row[1],
                    :price => row[2],
                    :note_id => row[3])
  end
  end




end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  # before_action :correct_user, only: [:edit, :update]
  before_action :set_note, only: [:show, :edit, :update, :destroy ]
 

  # before_action :search, only: [:index, :export_csv]
  User = Struct.new(:name, :email)
  

    def index
    @q        = Note.ransack(params[:q])
    @number = @q.result(distinct: true).order(created_at: :desc)
    if params[:export_csv]
    @q        = Note.ransack(params[:q])
    @notes    = @q.result(distinct: true).order(created_at: :desc)
    send_data @notes.to_csv, filename: "案件CSV_#{Time.current.strftime('%Y%m%d')}.csv"
    end
   
    @q        = Note.ransack(params[:q])
    @notes    = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(20)

    end

  def show
  end

 def create
    @note = current_user.notes.build(note_params)
   
      if @note.save
      	user = User.new("mail",@note)
        NoteMailer.delay.note_email(user, @note)
      redirect_to @note, notice: "案件が保存されました"
      else
        @notes = Note.all.order(created_at: :desc).page(params[:page]).per(6)
        render 'home/top'
      end 
   
 end

  def edit
  end

  def update
    if @note.update(note_params)
      NoteMailer.delay.note_email(current_user,@note)
      redirect_to @note, notice: "案件が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to root_path
  end
  
  def import
  
  Note.import(params[:file])
  redirect_to root_path, notice: '案件をインポートしました'
  end
    # def import
    # @note = Note.find(params[:id])
    # Proposal.import(@note, proposal_params[:proposal])
    #     # Code.import(@software, proposal_params[:proposal])

    # redirect_to root_path, notice: 'Codes were successfully uploaded!'
    # end
    
  private
  
  

    def set_note
      @note = Note.find(params[:id])
    end
    
    
    def note_params
      params.require(:note).permit(:title, :sales_company,
      :end_user, :delivery_day, :content, :status, :miss,
      proposals_attributes: [:id, :model, :quantity, :price, :_destroy])
    end

    def correct_user
      note = Note.find(params[:id])
      if !current_user?(note.user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end
    
     
    
   
    
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>

  <% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @note.errors.count %>件のエラー:</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  市場<br>
  <%= f.select :title, [["医療", "医療"], ["物流", "物流"], ["小売", "小売"], ["FA", "FA"], ["レンタル", "レンタル"], ["その他", "その他"]], :include_blank => true %><br>
  <!--< %= f.text_field :title, { class: "form-control title-field" } %>-->
  販社
  <%= f.text_field :sales_company, { class: "form-control title-field" } %>
  E/U
  <%= f.text_field :end_user, { class: "form-control title-field" } %>
  
  
 
    <%= f.fields_for :proposals do |proposal| %>
      <%= render 'proposal_fields', f: proposal %>
    <% end %>
    
    <div id="links">
      <%= link_to_add_association "提案機種を追加", f, :proposals, { class: "btn2 destroy-btn" } %>
    </div>
     
    
  納期
  <%= f.text_field :delivery_day, { class: "form-control title-field datepicker" } %>
  内容
  <%= f.text_area :content, { class: "form-control content-field" } %>

<label><%= f.radio_button :status, '提案' %>提案</label>  
<label><%= f.radio_button :status, '継続' %>継続</label>
<label><%= f.radio_button :status, '受注' %>受注</label>
<label id="login-show" class="login"><%= f.radio_button :status, '失注' %>失注</label>

  <br>
  <%= f.submit "保存", class: "btn primary-btn", data: { disable_with: '保存中･･･' } %>





  <div class="signup-modal-wrapper">
    
  </div>
  <div class="close-modal">
        <i class="fa fa-2x fa-times"></i>
      </div>

  
  <div id="login-modal"  class="login-modal-wrapper">

    <div class="modal">
   
      <div class="close-modal">
        <i class="fa fa-2x fa-times"></i>
      </div>
      <div id="login-form">
        <h2>失注理由</h2>
        <form action="#">
          <%= f.text_area :miss, { class: "form-control1 content-field" } %>
          
            <%= f.submit "保存", { class: "btn primary-btn" } %>

        </form>
      </div>
    </div>
    </div>
    
    


<!--  <h2>Import Products</h2>-->
<!--< %= form_tag import_notes_path, multipart: true do %>-->
<!--  < %= file_field_tag :file %>-->
<!--  < %= submit_tag "Import" %>-->
<!--< % end %>-->

<% end %>

app/views/notes/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for(@note, remote: true) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">失注理由</h4>
      </div>
      <div class="modal-body">
        <div class="field">
          <%= f.label :content %><br>
          <%= f.text_field :content %>
        </div>
      </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
           <%= f.submit "保存", { class: "btn primary-btn" } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/notes/_note.html.erb
<li>  
  <%= image_for(note.user) %>
  <span class="user-name">
    <%= note.user.name+"さん" %>
  </span>
  <span class="content">
    <%= link_to note.title, note_path(note.id) %>

  </span>
  <span>
    <%= note.created_at.strftime("%Y-%m-%d") %>
  </span>
    

</li>

app/views/notes/_proposal_fields.html.erb
<div class = "nested-fields">

      機種
      <%= f.text_field :model, {placeholder: "半角で入力してください", class: "form-control title-field" } %>
      台数
      <%= f.telephone_field :quantity, { placeholder: "半角で入力してください", class: "form-control title-field hankaku" } %>
      価格
      <%= f.telephone_field :price, {placeholder: "半で入力してください", class: "form-control title-field hankaku" } %>
     
      <%= link_to_remove_association "-", f, { class: "btn1 sakujo-btn" } %>

</div>

app/views/notes/_reminder.html.erb
<li>  
 
  
  <span class="content">
    <%= link_to note.sales_company, note_path(note.id) %> 経由
    <br><%= note.end_user %> 向け案件
  </span>
  <span>
    納期：<%= note.delivery_day %>
  </span>
    

</li>

app/views/notes/_save.js.erb
$(".note-index").html("<%= escape_javascript(render 'edit') %>")
$("#note-modal").modal("hide")

app/views/notes/_sendnote.html.erb
<li>
  <%= image_for(note.user) %>
  <span class="user-name">
    <%= link_to "案件ID：" + note.id.to_s, note_path(note.id) %>　<%= note.user.name+"さん" %>
  </span>
  <span class="content">
     <%= note.sales_company %> →
    <%= note.end_user %>

  </span>
  <span>
    登録日：<%= note.created_at.strftime("%Y-%m-%d") %>
  </span>
    

</li>

app/views/notes/edit.html.erb
<h1>投稿を編集する</h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<div class="panel panel-default">
 <div class="panel-heading">
    <div class="panel-title">検索</div>
  </div>


<div class="panel-body">

<%= search_form_for(@q, method: :get, url: "#result") do |f| %>


<div class="containers"> 


  <div class="row">  
    

     <div class="col-sm-4">
      <div class="form-group">
        担当　<%= f.select :user_name_cont, User.all.map{|t| [t.name, t.name]}, :include_blank => true %>
       
         <div class="margin-left">市場</div>　<%= f.select :title_eq, [["医療", "医療"], ["物流", "物流"], ["小売", "小売"], ["FA", "FA"], ["レンタル", "レンタル"], ["その他", "その他"]], :include_blank => true %>
             <!--<div class = "float-right" >-->

 
    <label class="margin-left"><%= f.check_box :status_eq_any, {multiple: true}, '提案',nil %>提案</label>
    <label><%= f.check_box :status_eq_any, {multiple: true}, '継続',nil %>継続</label>
    <label><%= f.check_box :status_eq_any, {multiple: true}, '受注',nil %>受注</label>
    <label><%= f.check_box :status_eq_any, {multiple: true}, '失注',nil %>失注</label>
     

    <!--</div>-->
       </div>
    </div>
  
  
    <div class="col-sm-4">
      <div class="form-grup">
          販社　<%= f.text_field :sales_company_cont, { class: "search-form-control search-title-field float" } %>
        </div>
    </div>

  
    <div class="col-sm-4">
      <div class="form-group">
          ＥＵ　<%= f.text_field :end_user_cont, { class: "search-form-control search-title-field float" } %>
        </div>
    </div>
    
    

    <div class="col-sm-4">
      <div class="form-group">
      機種　<%= f.text_field :proposals_model_cont, { class: "search-form-control search-title-field float" }  %>
      </div>
    </div>
    
    <div class="col-sm-4">
      <div class="form-group">
      台数　<%= f.text_field :proposals_quantity_gteq, { class: "search-form-control search-title-field float2" } %>
        ～ <%= f.text_field :proposals_quantity_lteq, { class: "search-form-control search-title-field float2" } %>
      </div>
    </div>
      
      <div class="col-sm-4">
      <div class="form-group">
      価格　<%= f.text_field :proposals_price_gteq, { class: "search-form-control search-title-field float2" } %>
        ～  <%= f.text_field :proposals_price_lteq, { class: "search-form-control search-title-field float2" } %>
     </div>
    </div>


    <div class="col-sm-4">
      <div class="form-group">
        納期　<%= f.text_field :delivery_day_gteq, { class: "search-form-control search-title-field datepicker float2" } %>
         ～ <%= f.text_field :delivery_day_lteq, { class: "search-form-control search-title-field datepicker float2" } %>
       </div>
    </div>
    
    <div class="col-sm-12">
      <div class="form-group">
        内容
        <%= f.text_area :content_cont, { class: "search-form-control content-field" } %>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="form-group">
      総合　<%= f.text_field :sales_company_or_end_user_or_content_cont, {placeholder: "企業名を入力すると対象案件の総合検索が出来ます。", class: "search-form-control search-title-field float" }  %>
      </div>
    </div>
     <div class="col-sm-4">
          <div class="form-group">
            登録　<%= f.text_field :created_at_gteq, {placeholder: "案件登録日を検索出来ます。", class: "search-form-control search-title-field datepicker float2" } %>
             ～ <%= f.text_field :created_at_lteq, {placeholder: "+1日で検索してください。", class: "search-form-control search-title-field datepicker float2" } %>
           </div>
        </div>
         

 
    <%= f.submit '検索', class: "btn edit-btn bold" %>
    <%= link_to "クリア", url_for, class: "btn clear-btn margin-left" %>
    <!--< %= link_to 'CSV', import_notes_path(format: "csv"), class: 'btn csv-btn bold margin-left' %>-->
    <!--< %= link_to "CSV", products_path(format: "csv") %> |-->
    <%= f.button class: 'btn csv-btn margin-left', name: 'export_csv' do %>
        <i class="fa fa-file-text"></i> CSV
      <% end %>
    
    <!--< %= link_to 'CSV', params.merge({:format => :csv}), class: 'btn csv-btn bold margin-left' %>    -->
    
<% end %>

</div>
 </div>

 
</div>
 </div>

<!--<div class="spacer" id="result"></div>-->
<div id="result"></div>

<div class="page-header">
  <h1>案件数　<%= @number.count %>件</h1>
</div>

<div id="searchWrapper">

<table class="table table-striped">
  
  <thead>
    <tr>
      <th>#</th>
      <th width="33px">担当</th>
      <th>市場</th>
      <th>販社</th>
      <th>EU</th>
      <th>機種</th>
      <th>数量</th>
      <th>単価</th>
      <th>納期</th>
      <th>状態</th>
      
     
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
    <% note.proposals.each do |proposal| %>
      <tr>
        <td><%= link_to note.id, note_path(note.id) %></td>
        <td><%= note.user.name %></td>
        <td><%= note.title %></td>
        <td><%= note.sales_company %></td>
        <td><%= note.end_user %></td>
        <td><%= proposal.model %></td>
        <td><%= proposal.quantity %></td>
        <td><%= number_to_currency(proposal.price, :unit => "") %></td>
        <td><%= note.delivery_day %></td>
        <td><%= note.status %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-sm-12">
    <%= paginate @notes %>
  </div>
</div>

 </div>

app/views/notes/new.html.erb
<h1>新規投稿する</h1>
<%= render 'form' %>

app/views/notes/search.html.erb
<div class="panel panel-default">
 <div class="panel-heading">
    <div class="panel-title">検索</div>
  </div>
  <div class="panel-body">
   
    <%= search_form_for(@q, method: :get) do |f| %>
      <div class="row">
        <div class="col-sm-12">
          <div class="form-group">
            <%= f.label :営業担当 %>
            <%= f.text_field :attr_name, class: "form-control", placeholder: "完全一致" %>
          </div>
        </div>
        
        <div class="col-sm-12">
          <div class="form-group">
            <%= f.label :営業担当 %>
            <%= f.text_field :sales_company_eq, class: "form-control", placeholder: "完全一致" %>
          </div>
        </div>
        
        <div class="col-sm-12">
          <div class="form-group">
            <%= f.label :営業担当 %>
            <%= f.text_field :end_user, class: "form-control", placeholder: "完全一致" %>
          </div>
        </div>
        
        <div class="col-sm-12">
          <div class="form-group">
            <%= f.label :営業担当 %>
            <%= f.text_field :model_eq, class: "form-control", placeholder: "完全一致" %>
          </div>
        </div>
        
        <div class="col-sm-12">
          <div class="form-group">
            <%= f.label :営業担当 %>
            <%= f.text_field :quantity_eq, class: "form-control", placeholder: "完全一致" %>
          </div>
        </div>
        
        <div class="col-sm-12">
          <div class="form-group">
            <%= f.label :営業担当 %>
            <%= f.text_field :price_eq, class: "form-control", placeholder: "完全一致" %>
          </div>
        </div>
        
        <div class="col-sm-12">
          <div class="form-group">
            <%= f.label :案件詳細 %>
            <%= f.text_field :content_cont, class: "form-control", placeholder: "部分一致" %>
          </div>
        </div>
        <div class="col-sm-12">
          <div class="form-group">
            <%= f.label :name_or_description_cont %>
            <%= f.text_field :name_or_description_cont, class: "form-control", placeholder: "複数条件部分一致" %>
          </div>
        </div>
        <div class="col-sm-12">
          <div class="form-inline">
            <%= f.label :receipt_day %>
            <%= f.date_select :delivery_day_gt, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, class: "form-control" %>〜
            <%= f.date_select :delivery_day_lt, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, class: "form-control" %>
          </div>
        </div>
      </div>
      <%= f.submit '検索', notes_index_path, class: "btn btn-primary" %>
      <%= link_to 'クリア', url_for, class: "btn btn-default" %>
    <% end %>
  </div>
</div>
</div>

</div>



<div class="spacer"></div>
<%- model_class = note -%>
<div class="page-header">
  <h1>登録案件</h1>
</div>

    <div class="row">
  <div class="col-sm-12">
    <%= paginate @notes %>
  </div>
</div>
<table class="table table-striped">
  
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:user) %></th>
      <th><%= model_class.human_attribute_name(:product) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:stock) %></th>
      <th><%= model_class.human_attribute_name(:receipt_day) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <tr>
  
        <td><%= note.title %></td>
        <td><%= note.user %></td>
        <td><%= note.product %></td>
        <td><%= note.content %></td>
        <td><%= note.price %></td>
        <td><%= note.quantity %></td>
        <td><%= note.delivery_day %></td>
        <td><%= note.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_note_path(note), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      note_path(note),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_note_path,
            :class => 'btn btn-primary' %>



 タイトル
  <%= f.text_field :title, { class: "form-control title-field" } %>
  販社
  <%= f.text_field :sales_company, { class: "form-control title-field" } %>
  E/U
  <%= f.text_field :end_user, { class: "form-control title-field" } %>
  提案機種
  <%= f.text_field :model, { class: "form-control title-field" } %>
  台数
  <%= f.text_field :quantity, { class: "form-control title-field" } %>
  価格
  <%= f.text_field :price, { class: "form-control title-field" } %>
  
  予定納期
  <%= f.text_field :delivery_day, { class: "form-control datepicker" } %>

 

  <!--<!%= f.label :receipt_day %>-->
  <!--<!%= f.date_select :delivery_day_gt, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, { class: "form-control title-field" } %>~<br>-->
  <!--<!%= f.date_select :delivery_day_lt, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, { class: "form-control title-field" } %>-->
  内容
  <%= f.text_area :content, { class: "form-control content-field" } %>

app/views/notes/show.html.erb
<%= link_to "前画面に戻る", :back, class: "btn back-btn" %>
<% if @note.previous %><%= link_to "前案件へ", note_path(@note.previous), class: "btn back-btn" %><% end %>
<% if @note.next %><%= link_to "次案件へ", note_path(@note.next), class: "btn back-btn" %><% end %>
<div class="show-background">
<h2>担当・案件ID・登録日</h2>
<p><%= @note.user.name %>さん　案件ID：<%= @note.id %>　登録日：<%= @note.created_at.strftime("%Y年%m月%d日") %></p>
<h2>マーケット</h2>
<p><%= @note.title %></p>
<h2>販社</h2>
<p><%= @note.sales_company %></p>
<h2>E/U</h2>
<p><%= @note.end_user %></p>
<h2>提案</h2>
<table class ="table">
  <thead>
    <tr>
      <th>機種</th>
      <th>台数</th>
      <th>価格</th>
      <th>案件規模</th>
    </tr>
  </thead>
  <tbody>
<% @note.proposals.each do |proposal| %>
<tr>
  <td><p><%= proposal.model %></p></td>
  <td><p><%= proposal.quantity %>台</p></td>
  <td><p>@<%= number_to_currency(proposal.price, :unit => "")%></p></td>
  <td><p><%= number_to_currency(proposal.price*proposal.quantity, :unit => "円") %></p></td>
  </tr>
<% end %>
</tbody>
</table>
<h2>予定納期</h2>
<p><%= @note.delivery_day %></p>
<h2>内容</h2>
<%= simple_format @note.content %>
<h2>状態</h2>
<p><%= @note.status %></p>

<% if @note.miss.present? then %>
<h2>失注理由</h2>
<%= simple_format @note.miss %>
<% end %>

<% if @note.updated_by? %>
<h2>最終更新</h2>
<p><%= User.find(@note.updated_by).name %>さん 　更新日 <%= @note.updated_at.strftime("%Y年%m月%d日") %></p>
<% end %>


</div>


  <%= link_to "編集", edit_note_path(@note.id), class: "btn edit-btn" %>
  <%= link_to "削除", note_path(@note.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>

app/views/notes/update.js.erb
<%= render 'save' %>