config/routes.rb
Rails.application.routes.draw do
  resources :notes
  
  # get '/notes/index' => 'notes#index'
  
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_notes
    end
  end

  resources :notes, only: [:show, :create, :edit, :update, :destroy] do
    member do
      get :liking_users
    end
  end

  post '/like/:note_id' => 'likes#like', as: 'like'
  delete '/unlike/:note_id' => 'likes#unlike', as: 'unlike'
  

  
  root 'home#top'
  get '/about' => 'home#about'
  
  resources :notes, :proposals do
  collection do
    post :import
  end
end

class CsvExportConstraint
  def self.matches?(request)
    request.params.has_key?(:export_csv)
  end
end

Rails.application.routes.draw do
  # root 'notes#index'

  resources :notes, only: [:index] do
    collection do
      get :index, action: :export_csv, constraints: CsvExportConstraint
      get :index
    end
  end
end

  
  
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :note

end

app/controllers/likes_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
      

  include ApplicationHelper

  private
  # 以下の1行は消さないでください
  def default_url_options() {instanceId: 'c2497291e8'}.merge(super) end


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end 
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_links.html.erb
<% if current_user.likes.find_by(note_id: note.id) %>
    <%= link_to 'いいね！を取り消す', unlike_path(note.id), method: :delete, remote: true %>
  <% else %>
    <%= link_to 'いいね！', like_path(note.id), method: :post, remote: true %>
<% end %>

app/views/likes/like.js.erb
<!-- １行目を削除し、コードを貼り付けてください -->
<!--render()の引数でパーシャルを呼び出し、変数noteに@noteを渡してください-->
$('#like-link').html('<%= escape_javascript(render("likes/like_links",note: @note  )) %>');
$('#like-count').html('<%= @note.likes.count %>');

app/views/likes/unlike.js.erb
<!-- １行目を削除し、コードを貼り付けてください -->
<!--render()の引数でパーシャルを呼び出し、変数noteに@noteを渡してください-->
$('#like-link').html('<%= escape_javascript(render("likes/like_links",note: @note  )) %>');
$('#like-count').html('<%= @note.likes.count %>');