config/routes.rb
Rails.application.routes.draw do
  resources :notes
  
  # get '/notes/index' => 'notes#index'
  
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_notes
    end
  end

  resources :notes, only: [:show, :create, :edit, :update, :destroy] do
    member do
      get :liking_users
    end
  end

  post '/like/:note_id' => 'likes#like', as: 'like'
  delete '/unlike/:note_id' => 'likes#unlike', as: 'unlike'
  

  
  root 'home#top'
  get '/about' => 'home#about'
  
  resources :notes, :proposals do
  collection do
    post :import
  end
end

class CsvExportConstraint
  def self.matches?(request)
    request.params.has_key?(:export_csv)
  end
end

Rails.application.routes.draw do
  # root 'notes#index'

  resources :notes, only: [:index] do
    collection do
      get :index, action: :export_csv, constraints: CsvExportConstraint
      get :index
    end
  end
end

  
  
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable
  has_many :notes
  has_many :proposals, through: :notes
  # has_many :addresses, through: :notes
  # has_many :likes
  # has_many :like_notes, through: :likes, source: :note

  validates :name, presence: true
  # deviseのvalidatableによって以下と同じバリデーションが設定されているのでコメントアウトしています
  # validates :email, presence: true, uniqueness: true

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]


  def index
    @users = User.all
  end

    def show
    @q        = @user.notes.ransack(:status_eq => "提案", :delivery_day_lt => Date.today)
    @reminders = @q
                  .result(distinct: true)
                  .order(updated_at: :desc)
                  .page(params[:page]).per(5)
    @notes = @user.notes.order(updated_at: :desc).page(params[:page]).per(5)
    @title = "さんの案件一覧"
    end

  def edit
  end

  def update
    file = params[:user][:image]
    @user.set_image(file)

    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報が更新されました'
    else
      render :edit
    end
  end

  # def like_notes
  #   @notes = @user.like_notes
  #   @title = "いいね！一覧"
  #   render :show
  # end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end

    def correct_user
      user = User.find(params[:id])
      if !current_user?(user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def image_for(user)
    if user.image
      image_tag "/user_images/#{user.image}", class: "profile_img"
    else
      image_tag "wanko.jpg", class: "profile_img"
    end
  end
  
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
       <p><%= @user.errors.count %>件のエラーがあります。</p>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  名前
  <%= f.text_field :name, class: "form-control name-field" %>

  メールアドレス
  <%= f.text_field :email, class: "form-control email-field" %>
  
  プロフィール画像
  <%= f.file_field :image, class: "form-control image-field" %>

  <%= f.submit '保存', class: "btn primary-btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= image_for(user) %>
  <%= link_to user.name+"さん", user %> |
  <%= user.email %>
</li>

app/views/users/edit.html.erb
<h1>ユーザーの編集</h1>

<%= render 'form' %>

<%= link_to '営業担当一覧へ', users_path %>

app/views/users/index.html.erb
<h1 class="heading">登録一覧</h1>

<ul class="user-list">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<h1>新規ユーザー作成</h1>

<%= render 'form' %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<aside class="userSidebar">  
  <section>
    <span class="label">プロフィール画像</span>
    <h3 class="user-info">
      <%= image_for(@user) %>
    </h3>
  </section>

  <section>
    <span class="label">ユーザー</span>
    <h3 class="user-info"><%= @user.name %>さん</h3>
  </section>
  
  <section>
    <span class="label">メールアドレス</span>
    <h3 class="user-info"><%= @user.email %></h3>
  </section>


  <% if current_user?(@user) %>
    <section>
      <small><%= link_to 'プロフィールを編集', edit_user_path(@user) %></small>
    </section>
  <% end %>

</aside>


<ul class="userNotes">
  <h2><%= @user.name + @title %></h2>
  <% @notes.each do |note| %>
  <%= render  "notes/sendnote",note: note %>
  <% end %>
  <%= paginate @notes %>

<!--< % if current_user?(@user) %>-->
<!--  <p>-->
<!--< %= mail_to 'user@example.com', ' メールを起動(まだ使えません）', :class => "fa fa-envelope-o" %>-->

<!--</p>-->
<!--< % end %>-->


</ul>

<ul class="userNotes">
  <h2 class="userReminder">リマインダー(更新してください)</h2>
  
  <% @reminders.each do |note| %>
  <%= render "notes/reminder",note: note %>
  <% end %>
  <%= paginate @reminders %>
</ul>