config/routes.rb
Rails.application.routes.draw do
  resources :notes
  
  # get '/notes/index' => 'notes#index'
  
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_notes
    end
  end

  resources :notes, only: [:show, :create, :edit, :update, :destroy] do
    member do
      get :liking_users
    end
  end

  post '/like/:note_id' => 'likes#like', as: 'like'
  delete '/unlike/:note_id' => 'likes#unlike', as: 'unlike'
  

  
  root 'home#top'
  get '/about' => 'home#about'
  
  resources :notes, :proposals do
  collection do
    post :import
  end
end

class CsvExportConstraint
  def self.matches?(request)
    request.params.has_key?(:export_csv)
  end
end

Rails.application.routes.draw do
  # root 'notes#index'

  resources :notes, only: [:index] do
    collection do
      get :index, action: :export_csv, constraints: CsvExportConstraint
      get :index
    end
  end
end

  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>Imager案件DB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar">
    <div class="container">
      <div id="logo"><%= link_to "Imager案件DB", root_path %></div>
      <% if user_signed_in? %>
        <ul class="header-right">
          <li><%= link_to "HOME", root_path %></li>
          <li><%= link_to "案件検索", notes_path %></li>
          <li><%= link_to "登録一覧", users_path %></li>
          <li><%= link_to "個人ページ", current_user %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      <% end %>
    </div>
  </header>
  
  <div class="container">
    <p class="alert alert-success"><%= notice %></p>
    <p class="alert alert-danger"><%= alert %></p>
    <%= yield %>
  </div>

  <div class="container">
    <footer class="footer">
      <div class="small">
        &copy; 株式会社 イメージャー all rights reserved. 掲載の情報・画像など、すべてのコンテンツの無断複写・転載を禁じます
      </div>
    </footer>
  </div>
</body>
</html>